version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/K8sResourceResizer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "hcayada"
    assignees:
      - "hcayada" 